### PR TITLE
Use print function instead of print statement.

### PR DESCRIPTION
**Pull request by kunalparmar**
print statement no longer exists in Python 3.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @kunalparmar has signed the CLA. Thanks for the pull request!

**Comment by Jeff-Meadows** [comment]
:+1:

**Comment by jmoldow** [comment]
:-1: 

Add ``from __future__ import print_function`` for Python2 compatibility.

**Comment by jmoldow** [comment]
:+1: :+1: 

But FYI for the future, you can combine two ``from __future__`` statements into one, the same way you can do with normal imports.

**Pull request merged**
